* Notebook
** 220815 -- Initial Draft Plots Complete

The draft of the initial plots are all complete.  These might be subject to some slight further edits as we move forward, but should more or less be near final for initial submission.  

** 220814 -- Updating Sampling Plots

*Updates*

I am pretty happy now with the sampling plots.

I realized if we are going proof of concept, I shouldn't restrict myself to a super short 2-um pulse, but I should make it short enough to reduce the amount of needed explanation about the sampling.

I now simulate the response with a driver having:
 - 2-um center frequency
 - 15 fs duration (Gaussian FWHM)
 - Peak field of 7 GV/m

Then we compare in the time-domain the sampled fields and gabor transforms to indicate that all salient features of the time-frequency information up to the 9th harmonic should be able to be captured.

The only issue remaining is the plasmonic response of the material, but I think this can be overcome with further engineering.

*What I want to Do*

Now I want to compile the sampling plot.  I am imagining a three-panel plot.

The top would be a wide panel showing the time-domain fields.  This would be:

 - Sampled fields
 - Actual fields
 - The driving field (for time reference)

Under this top (a) panel, would be (b) and (c) side by side (left and right) that would be the Gabor transforms of the

 - Actual fields
 - Sampled fields
* Tasks
** TODO Update paper title and citation in the README.
** TODO Add description of files contained within the repository.  

